import { defaultExportOptions, type ExportDataBundle } from "@/lib/export/types"

export function sampleExportBundle(overrides: Partial<ExportDataBundle> = {}): ExportDataBundle {
  return {
    metadata: {
      generatedAt: "2026-06-04T10:00:00.000Z",
      generatedAtFormatted: "06.04.2026 10:00",
      title: "Investment report",
      subtitle: "Demo export",
      appUrl: "https://app.example.com",
      period: {
        type: "all",
        from: "1970-01-01T00:00:00.000Z",
        to: "2026-06-04T10:00:00.000Z",
        fromFormatted: "01.01.1970",
        toFormatted: "06.04.2026",
        label: "All time",
      },
      dataSource: "PostgreSQL/Prisma",
      selectedSections: ["portfolioSummary", "accounts", "holdings", "transactions", "analytics", "metadata"],
      format: "xlsx",
      language: "en",
      currency: "USD",
      pageSize: "A4",
      orientation: "portrait",
      options: defaultExportOptions,
      warnings: [],
      accountScope: {
        type: "all",
        accountId: null,
        accountName: null,
        accountCurrency: null,
        baseCurrency: "USD",
        conversionWarnings: [],
        rateSource: "CBR",
        rateDate: null,
      },
    },
    user: {
      email: "user@example.com",
      username: "User",
      role: "user",
    },
    portfolioSummary: {
      totalPortfolioValue: 12500,
      totalInvested: 10000,
      cashBalance: 500,
      unrealizedPnL: 2500,
      realizedPnL: 0,
      totalPnL: 2500,
      pnlPercent: 25,
      assetCount: 1,
      largestPosition: { symbol: "AAPL", name: "Apple", type: "stock", value: 12000, percent: 96 },
      diversificationScore: 25,
      updatedAt: "2026-06-04T10:00:00.000Z",
      source: "portfolio_assets",
    },
    accounts: [{ name: "Brokerage", type: "brokerage", balance: 500, currency: "USD", createdAt: "2026-01-01T00:00:00.000Z" }],
    assets: [{ symbol: "AAPL", name: "Apple", type: "stock", currentPrice: 200, currency: "USD", updatedAt: "2026-06-04T10:00:00.000Z" }],
    holdings: [{
      portfolio: "Main",
      symbol: "AAPL",
      name: "Apple",
      type: "stock",
      quantity: 60,
      averageBuyPrice: 150,
      currentPrice: 200,
      marketValue: 12000,
      currency: "USD",
    }],
    transactions: [{
      date: "2026-01-10T00:00:00.000Z",
      type: "buy",
      symbol: "AAPL",
      assetName: "Apple",
      quantity: 60,
      pricePerUnit: 150,
      totalAmount: 9000,
      fee: 1,
      currency: "USD",
      account: "Brokerage",
      notes: "Initial buy",
    }],
    analytics: null,
    qrCodeDataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
    qrCodeSvg: "<svg />",
    chartSnapshots: [],
    ...overrides,
  }
}
